<form id="editMainForm" onsubmit="false;" class="form form-horizontal" method="post" enctype="multipart/form-data">
    <div class="body">
        <div class="row clearfix">
            <div class="col-sm-6"><div class="form-group"><label>Template Name <span class="text-danger">*</span></label><div class="form-line"><input type="text" class="form-control" value="{{$edit->name}}" name="name"></div></div></div>
            <div class="col-sm-6"><div class="form-group"><label>Certificate Name</label><div class="form-line"><input type="text" class="form-control" value="{{$edit->cert_name}}" name="cert_name"></div></div></div>
            <div class="col-sm-6"><div class="form-group"><label>Logo</label><div class="form-line"><input type="file" class="form-control" name="logo"></div>@if($edit->logo)<small class="text-muted">Current: {{$edit->logo}}</small>@endif</div></div>
            <div class="col-sm-6"><div class="form-group"><label>Company Name</label><div class="form-line"><input type="text" class="form-control" value="{{$edit->company_name}}" name="company_name"></div></div></div>
            <div class="col-sm-6"><div class="form-group"><label>Heading</label><div class="form-line"><input type="text" class="form-control" value="{{$edit->heading}}" name="heading"></div></div></div>
            <div class="col-sm-6"><div class="form-group"><label>Sub Heading</label><div class="form-line"><input type="text" class="form-control" value="{{$edit->sub_heading}}" name="sub_heading"></div></div></div>
            <div class="col-sm-6"><div class="form-group"><label>Sub Heading Two</label><div class="form-line"><input type="text" class="form-control" value="{{$edit->sub_heading_two}}" name="sub_heading_two"></div></div></div>
            <div class="col-sm-6"><div class="form-group"><label>Cert Number Format <span class="text-danger">*</span></label><div class="form-line"><input type="text" class="form-control" value="{{$edit->cert_num_format}}" name="cert_num_format"></div></div></div>
            <div class="col-sm-6"><div class="form-group"><label>Certificate Template(image width:3600px* height:2550px) <span class="text-danger">*</span></label><div class="form-line"><input type="file" class="form-control" name="template_doc"></div>@if($edit->template_doc)<small class="text-muted">Current: {{$edit->template_doc}}</small>@endif</div></div>
            <div class="col-sm-6"><div class="form-group"><label>Cert ID Display</label><div class="form-line"><input type="text" class="form-control" value="{{$edit->cert_id_display}}" name="cert_id_display"></div></div></div>
            <div class="col-sm-6"><div class="form-group"><label>Stamp</label><div class="form-line"><input type="file" class="form-control" name="stamp"></div>@if($edit->stamp)<small class="text-muted">Current: {{$edit->stamp}}</small>@endif</div></div>
            <?php 
                $cert_name_pos = json_decode($edit->cert_name_pos, true) ?? ['x_pos' => 0, 'y_pos' => 0];
                $logo_pos = json_decode($edit->logo_pos, true) ?? ['x_pos' => 0, 'y_pos' => 0];
                $company_name_pos = json_decode($edit->company_name_pos, true) ?? ['x_pos' => 0, 'y_pos' => 0];
                $heading_pos = json_decode($edit->heading_pos, true) ?? ['x_pos' => 0, 'y_pos' => 0];
                $sub_heading_pos = json_decode($edit->sub_heading_pos, true) ?? ['x_pos' => 0, 'y_pos' => 0];
                $sub_heading_two_pos = json_decode($edit->sub_heading_two_pos, true) ?? ['x_pos' => 0, 'y_pos' => 0];
                $cert_num_format_pos = json_decode($edit->cert_num_format_pos, true) ?? ['x_pos' => 0, 'y_pos' => 0];
                $cert_id_display_pos = json_decode($edit->cert_id_display_pos, true) ?? ['x_pos' => 0, 'y_pos' => 0];
                $stamp_pos = json_decode($edit->stamp_pos, true) ?? ['x_pos' => 0, 'y_pos' => 0];
                $qr_code_pos = json_decode($edit->qr_code_pos, true) ?? ['x_pos' => 0, 'y_pos' => 0];
            ?>
            <div class="col-sm-12"><div class="form-group"><label>Cert Name Position</label><div class="row clearfix"><div class="col-sm-6"><div class="form-line"><input type="number" class="form-control" value="{{$cert_name_pos['x_pos']}}" name="cert_name_pos_x" placeholder="X Position"></div></div><div class="col-sm-6"><div class="form-line"><input type="number" class="form-control" value="{{$cert_name_pos['y_pos']}}" name="cert_name_pos_y" placeholder="Y Position"></div></div></div></div></div>
            <div class="col-sm-12"><div class="form-group"><label>Logo Position</label><div class="row clearfix"><div class="col-sm-6"><div class="form-line"><input type="number" class="form-control" value="{{$logo_pos['x_pos']}}" name="logo_pos_x" placeholder="X Position"></div></div><div class="col-sm-6"><div class="form-line"><input type="number" class="form-control" value="{{$logo_pos['y_pos']}}" name="logo_pos_y" placeholder="Y Position"></div></div></div></div></div>
            <div class="col-sm-12"><div class="form-group"><label>Company Name Position</label><div class="row clearfix"><div class="col-sm-6"><div class="form-line"><input type="number" class="form-control" value="{{$company_name_pos['x_pos']}}" name="company_name_pos_x" placeholder="X Position"></div></div><div class="col-sm-6"><div class="form-line"><input type="number" class="form-control" value="{{$company_name_pos['y_pos']}}" name="company_name_pos_y" placeholder="Y Position"></div></div></div></div></div>
            <div class="col-sm-12"><div class="form-group"><label>Heading Position</label><div class="row clearfix"><div class="col-sm-6"><div class="form-line"><input type="number" class="form-control" value="{{$heading_pos['x_pos']}}" name="heading_pos_x" placeholder="X Position"></div></div><div class="col-sm-6"><div class="form-line"><input type="number" class="form-control" value="{{$heading_pos['y_pos']}}" name="heading_pos_y" placeholder="Y Position"></div></div></div></div></div>
            <div class="col-sm-12"><div class="form-group"><label>Sub Heading Position</label><div class="row clearfix"><div class="col-sm-6"><div class="form-line"><input type="number" class="form-control" value="{{$sub_heading_pos['x_pos']}}" name="sub_heading_pos_x" placeholder="X Position"></div></div><div class="col-sm-6"><div class="form-line"><input type="number" class="form-control" value="{{$sub_heading_pos['y_pos']}}" name="sub_heading_pos_y" placeholder="Y Position"></div></div></div></div></div>
            <div class="col-sm-12"><div class="form-group"><label>Sub Heading Two Position</label><div class="row clearfix"><div class="col-sm-6"><div class="form-line"><input type="number" class="form-control" value="{{$sub_heading_two_pos['x_pos']}}" name="sub_heading_two_pos_x" placeholder="X Position"></div></div><div class="col-sm-6"><div class="form-line"><input type="number" class="form-control" value="{{$sub_heading_two_pos['y_pos']}}" name="sub_heading_two_pos_y" placeholder="Y Position"></div></div></div></div></div>
            <div class="col-sm-12"><div class="form-group"><label>Cert Number Format Position</label><div class="row clearfix"><div class="col-sm-6"><div class="form-line"><input type="number" class="form-control" value="{{$cert_num_format_pos['x_pos']}}" name="cert_num_format_pos_x" placeholder="X Position"></div></div><div class="col-sm-6"><div class="form-line"><input type="number" class="form-control" value="{{$cert_num_format_pos['y_pos']}}" name="cert_num_format_pos_y" placeholder="Y Position"></div></div></div></div></div>
            <div class="col-sm-12"><div class="form-group"><label>Cert ID Display Position</label><div class="row clearfix"><div class="col-sm-6"><div class="form-line"><input type="number" class="form-control" value="{{$cert_id_display_pos['x_pos']}}" name="cert_id_display_pos_x" placeholder="X Position"></div></div><div class="col-sm-6"><div class="form-line"><input type="number" class="form-control" value="{{$cert_id_display_pos['y_pos']}}" name="cert_id_display_pos_y" placeholder="Y Position"></div></div></div></div></div>
            <div class="col-sm-12"><div class="form-group"><label>Stamp Position</label><div class="row clearfix"><div class="col-sm-6"><div class="form-line"><input type="number" class="form-control" value="{{$stamp_pos['x_pos']}}" name="stamp_pos_x" placeholder="X Position"></div></div><div class="col-sm-6"><div class="form-line"><input type="number" class="form-control" value="{{$stamp_pos['y_pos']}}" name="stamp_pos_y" placeholder="Y Position"></div></div></div></div></div>
            <div class="col-sm-12"><div class="form-group"><label>QR Code Position</label><div class="row clearfix"><div class="col-sm-6"><div class="form-line"><input type="number" class="form-control" value="{{$qr_code_pos['x_pos']}}" name="qr_code_pos_x" placeholder="X Position"></div></div><div class="col-sm-6"><div class="form-line"><input type="number" class="form-control" value="{{$qr_code_pos['y_pos']}}" name="qr_code_pos_y" placeholder="Y Position"></div></div></div></div></div>       
        </div>
    </div>
    <input type="hidden" name="edit_id" value="{{$edit->id}}">
</form>
